## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('distancebased', ['internet', 'config-store', 'point-to-point', 'wifi', 'applications'])
    module.includes = '.'
    module.source = [
        'model/db-header.cc',
        'model/db-routing-protocol.cc',
        'model/db-duplicate-detection.cc',
        'helper/db-helper.cc',
        ]



    headers = bld(features='ns3header')
    headers.module = 'distancebased'
    headers.source = [
        'model/db-routing-protocol.h',
        'model/db-header.h',
        'model/db-duplicate-detection.h',
        'helper/db-helper.h',
        ]




